image: docker:20.10.16

services:
  - docker:20.10.16-dind

stages:
  - build-app
  - deploy-app

build-app:
  stage: build-app
  script: 
    - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin ${CI_REGISTRY}
    - docker build -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}" .
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
  only:
    refs:
      - master
      - main
  
gitops-monetab:
  stage: deploy-app
  dependencies:
    - build-app
  variables:
    HELM_IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  only:
    refs:
      - master
      - main
  before_script:
    - apk add --no-cache git
  script:
    - |
      echo "Configuration de Git pour GitOps"
      git config --global user.email "gitops@gitops.com"
      git config --global user.name "gitops"
